# Generated by Django 4.1.2 on 2025-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('New', 'NeW'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='New', max_length=150),
        ),
    ]
